name: Delete custom domain

jobs:
  delete_domain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Delete custom domain
      run: |
        git push origin --delete custom-domain
        git push --force origin :custom-domain
